# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import stream_pb2 as stream__pb2


class PostControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Stream = channel.unary_stream(
                '/stream.PostController/Stream',
                request_serializer=stream__pb2.CallInfo.SerializeToString,
                response_deserializer=stream__pb2.CallInfo.FromString,
                )
        self.Cancel = channel.unary_stream(
                '/stream.PostController/Cancel',
                request_serializer=stream__pb2.Cancel.SerializeToString,
                response_deserializer=stream__pb2.Cancel.FromString,
                )


class PostControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Stream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PostControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Stream': grpc.unary_stream_rpc_method_handler(
                    servicer.Stream,
                    request_deserializer=stream__pb2.CallInfo.FromString,
                    response_serializer=stream__pb2.CallInfo.SerializeToString,
            ),
            'Cancel': grpc.unary_stream_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=stream__pb2.Cancel.FromString,
                    response_serializer=stream__pb2.Cancel.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stream.PostController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PostController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Stream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/stream.PostController/Stream',
            stream__pb2.CallInfo.SerializeToString,
            stream__pb2.CallInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/stream.PostController/cancel',
            stream__pb2.Cancel.SerializeToString,
            stream__pb2.Cancel.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
