# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stream.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cstream.proto\x12\x06stream\".\n\x08\x43\x61llInfo\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\x05\"\x1c\n\x06\x43\x61ncel\x12\x12\n\nsession_id\x18\x01 \x01(\t2p\n\x0ePostController\x12\x30\n\x06Stream\x12\x10.stream.CallInfo\x1a\x10.stream.CallInfo\"\x00\x30\x01\x12,\n\x06\x63\x61ncel\x12\x0e.stream.Cancel\x1a\x0e.stream.Cancel\"\x00\x30\x01\x62\x06proto3')



_CALLINFO = DESCRIPTOR.message_types_by_name['CallInfo']
_CANCEL = DESCRIPTOR.message_types_by_name['Cancel']
CallInfo = _reflection.GeneratedProtocolMessageType('CallInfo', (_message.Message,), {
  'DESCRIPTOR' : _CALLINFO,
  '__module__' : 'stream_pb2'
  # @@protoc_insertion_point(class_scope:stream.CallInfo)
  })
_sym_db.RegisterMessage(CallInfo)

Cancel = _reflection.GeneratedProtocolMessageType('Cancel', (_message.Message,), {
  'DESCRIPTOR' : _CANCEL,
  '__module__' : 'stream_pb2'
  # @@protoc_insertion_point(class_scope:stream.Cancel)
  })
_sym_db.RegisterMessage(Cancel)

_POSTCONTROLLER = DESCRIPTOR.services_by_name['PostController']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CALLINFO._serialized_start=24
  _CALLINFO._serialized_end=70
  _CANCEL._serialized_start=72
  _CANCEL._serialized_end=100
  _POSTCONTROLLER._serialized_start=102
  _POSTCONTROLLER._serialized_end=214
# @@protoc_insertion_point(module_scope)
